services:
- docker
script:
- source bin/travis
- export GIT_TAG=paper-$TRAVIS_BRANCH-$(date -u "+%m-%d")-r$TRAVIS_BUILD_NUMBER
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- echo -n $GIT_TAG > version
- git commit -m "Set build VERSION number" version
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
branches:
  except:
  - "/^paper-[0-9a-z\\-]*/"
  - "development"
deploy:
  provider: releases
  cleanup: false
  file_glob: true
  file:
  - rel/*
  edge: true
